# -*- coding: utf-8 -*-
"""Trabajo .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kIwcKXoQKDA40La23ha_tP_2uPI4_aJs

###Cargar datos con la función read_csv de pandas.
"""

import pandas as pd 
import os

"""###Definir el directorio donde se encuentra el datasets"""

import pandas as pd 
import os 
mainpath = "drive/MyDrive/Trabajo"
filename = "Catalogo1960_2021.xlsx"
fullpath = os.path.join(mainpath,filename)
df = pd.read_excel(fullpath)
df.head(2000)

"""###Cargar los datos"""

df = pd.read_csv(filename)
df.head()